[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config_handler = { path = "../config_handler" }

actix-web = "4"
diesel = "1.4.8"